runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: public/images/favicon-32x32.png
  upload: public/images/favicon-32x32.png
- url: /img
  static_dir: public/img
- url: /images
  static_dir: public/images
- url: /css
  static_dir: public/css
- url: /js
  static_dir: public/js
- url: /.*
  script: pywordfinder.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
  
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*\.db$
